[package]
name = "collision_sim"
version = "0.1.0"
authors = ["canteyc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sssf = "0.1.0"

[dev-dependencies]
approx = "0.5.0"